development:
  adapter: postgresql
  database: sivar_rals_todos_dev
  host: localhost
  username: ragar90
  password: jhlive

test:
  adapter: postgresql
  database: sivar_rals_todos_test
  host: localhost
  username: ragar90
  password: jhlive

production:
  adapter: postgresql
  database: sivar_rals_todos_prod
  host: localhost
  username: ragar90
  password: jhlive
